# Generated by Django 3.2 on 2021-04-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210409_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyClass',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('datestart', models.DateField(db_column='dateStart')),
                ('dateend', models.DateField(db_column='dateEnd')),
                ('firstname', models.CharField(db_column='FirstName', max_length=50, unique=True)),
                ('lastname', models.CharField(db_column='LastName', max_length=255, unique=True)),
                ('studentid', models.CharField(db_column='StudentID', max_length=14, unique=True)),
                ('classid', models.CharField(db_column='ClassID', max_length=14, unique=True)),
                ('classname', models.CharField(db_column='Class', max_length=100, unique=True)),
                ('classid2', models.CharField(db_column='ClassID2', max_length=100, unique=True)),
                ('grade', models.PositiveIntegerField(db_column='Grade')),
                ('assignment', models.PositiveIntegerField(db_column='Assignment')),
            ],
        ),
    ]
