# Generated by Django 3.2 on 2021-04-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_dummyclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dept', models.CharField(db_column='Dept', max_length=14, unique=True)),
                ('teacher', models.CharField(db_column='Teacher', max_length=255, unique=True)),
                ('className', models.CharField(db_column='ClassName', max_length=100, unique=True)),
                ('content', models.CharField(db_column='Content', max_length=100, unique=True)),
            ],
        ),
    ]
