# Generated by Django 3.2 on 2021-04-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210409_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookupcourse',
            name='coursecode',
            field=models.CharField(db_column='courseCode', max_length=15),
        ),
    ]
