# Generated by Django 3.2 on 2021-04-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_lookupcourse_coursecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookupcourse',
            name='coursename',
            field=models.CharField(db_column='coursename', max_length=50, unique=True),
        ),
    ]
