# Generated by Django 3.2 on 2021-04-10 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_lookupcourse_coursename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestudent',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.courseschedule'),
        ),
    ]
