# Generated by Django 3.2 on 2021-04-16 21:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_adminusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminUsers',
            new_name='AdminUser',
        ),
    ]
