# Generated by Django 3.2 on 2021-04-25 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210424_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lookupterm',
            name='term_status',
        ),
    ]
