# Generated by Django 3.2 on 2021-04-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_lookupterm_term_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookupterm',
            name='term',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='lookupterm',
            unique_together={('termstart', 'termend')},
        ),
    ]
