# Generated by Django 3.2 on 2021-05-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210425_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_withGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.PositiveIntegerField()),
                ('assignmentdate', models.DateField(db_column='assignmentDate')),
                ('duedate', models.DateField(db_column='dueDate')),
                ('description', models.TextField()),
                ('pointspossible', models.PositiveIntegerField(db_column='pointsPossible')),
                ('course_schedule_id', models.PositiveIntegerField()),
                ('pointsearned', models.PositiveIntegerField()),
                ('numbergrade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('username', models.CharField(max_length=150)),
            ],
        ),
    ]
