# Generated by Django 3.2 on 2021-05-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_assignment_withgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_withgrade',
            name='lettergrade',
            field=models.CharField(default=' ', max_length=2),
            preserve_default=False,
        ),
    ]
