# Generated by Django 3.2 on 2021-05-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_assignment_withgrade_lettergrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='dategraded',
            field=models.DateField(db_column='dateGraded', null=True),
        ),
    ]
