# Generated by Django 3.2 on 2021-05-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_studentsubmission_dategraded'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_withgrade',
            name='dategraded',
            field=models.DateField(db_column='dateGraded', null=True),
        ),
    ]
