# Generated by Django 3.2 on 2021-05-30 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210530_0855'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
