# Generated by Django 3.2 on 2021-05-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='submission',
            field=models.FileField(upload_to='submissions/'),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='submission',
            field=models.FileField(upload_to='submissions/'),
        ),
    ]
