# Generated by Django 3.2 on 2021-06-08 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_document'),
        ('app', '0022_auto_20210530_1005'),
        ('app', '0022_delete_document'),
    ]

    operations = [
    ]
