# Generated by Django 3.2 on 2021-06-08 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0023_merge_20210607_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassStudentGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_student_id', models.PositiveIntegerField()),
                ('course_schedule_id', models.PositiveIntegerField()),
                ('student_id', models.PositiveIntegerField()),
                ('first_name', models.CharField(db_column='Student first name', max_length=150)),
                ('last_name', models.CharField(db_column='Student last name', max_length=150)),
                ('userid', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=150)),
                ('coursegrade', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Course grade')),
                ('pointsEarned', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Points earned')),
                ('pointsPossible', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Points possible')),
                ('term', models.CharField(max_length=50)),
                ('termstart', models.DateField(db_column='termStart')),
                ('termend', models.DateField(db_column='termEnd')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedTeacherCS_withCounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_schedule_id', models.PositiveIntegerField()),
                ('course_id', models.PositiveIntegerField()),
                ('teacher_id', models.PositiveIntegerField()),
                ('term', models.CharField(max_length=50, unique=True)),
                ('termstart', models.DateField(db_column='termStart')),
                ('termend', models.DateField(db_column='termEnd')),
                ('coursename', models.CharField(db_column='coursename', max_length=50, unique=True)),
                ('coursecode', models.CharField(db_column='courseCode', max_length=15)),
                ('first_name', models.CharField(db_column='Teacher first name', max_length=150)),
                ('last_name', models.CharField(db_column='Teacher last name', max_length=150)),
                ('roster_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrentTeacherCS_withCounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_schedule_id', models.PositiveIntegerField()),
                ('course_id', models.PositiveIntegerField()),
                ('teacher_id', models.PositiveIntegerField()),
                ('term', models.CharField(max_length=50, unique=True)),
                ('termstart', models.DateField(db_column='termStart')),
                ('termend', models.DateField(db_column='termEnd')),
                ('coursename', models.CharField(db_column='coursename', max_length=50, unique=True)),
                ('coursecode', models.CharField(db_column='courseCode', max_length=15)),
                ('first_name', models.CharField(db_column='Teacher first name', max_length=150)),
                ('last_name', models.CharField(db_column='Teacher last name', max_length=150)),
                ('roster_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FutureTeacherCS_withCounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_schedule_id', models.PositiveIntegerField()),
                ('course_id', models.PositiveIntegerField()),
                ('teacher_id', models.PositiveIntegerField()),
                ('term', models.CharField(max_length=50, unique=True)),
                ('termstart', models.DateField(db_column='termStart')),
                ('termend', models.DateField(db_column='termEnd')),
                ('coursename', models.CharField(db_column='coursename', max_length=50, unique=True)),
                ('coursecode', models.CharField(db_column='courseCode', max_length=15)),
                ('first_name', models.CharField(db_column='Teacher first name', max_length=150)),
                ('last_name', models.CharField(db_column='Teacher last name', max_length=150)),
                ('roster_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourseListWithGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_student_id', models.PositiveIntegerField()),
                ('course_schedule_id', models.PositiveIntegerField()),
                ('student_id', models.PositiveIntegerField()),
                ('teacher', models.CharField(db_column='Teacher', max_length=150)),
                ('coursegrade', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Course grade')),
                ('pointsEarned', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Points earned')),
                ('pointsPossible', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Points possible')),
                ('term', models.CharField(max_length=50)),
                ('termstart', models.DateField(db_column='termStart')),
                ('termend', models.DateField(db_column='termEnd')),
                ('coursename', models.CharField(db_column='coursename', max_length=150, verbose_name='Course name')),
                ('screen', models.CharField(db_column='screen', max_length=10, verbose_name='Screen')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
        migrations.AlterField(
            model_name='assignment_withgrade',
            name='assignmentdate',
            field=models.DateField(db_column='assignmentDate', verbose_name='Date assigned'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='assignmentdate',
            field=models.DateField(db_column='assignmentDate', verbose_name='Assignment date'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='duedate',
            field=models.DateField(db_column='dueDate', verbose_name='Due date'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='pointspossible',
            field=models.PositiveIntegerField(db_column='pointsPossible', verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.lookupcourse', verbose_name='Course name'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Teacher'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.lookupterm', verbose_name='Term'),
        ),
        migrations.AlterField(
            model_name='coursestudent',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.courseschedule', verbose_name='Course name'),
        ),
        migrations.AlterField(
            model_name='coursestudent',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Course grade'),
        ),
        migrations.AlterField(
            model_name='coursestudent',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='lookupcourse',
            name='coursecode',
            field=models.CharField(db_column='courseCode', max_length=15, verbose_name='Course code'),
        ),
        migrations.AlterField(
            model_name='lookupcourse',
            name='coursename',
            field=models.CharField(db_column='coursename', max_length=50, unique=True, verbose_name='Course name'),
        ),
        migrations.AlterField(
            model_name='lookupcourse',
            name='department',
            field=models.ForeignKey(blank=True, db_column='department', null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.lookupdepartment', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.courseassignment', verbose_name='Assignment description'),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='dategraded',
            field=models.DateField(db_column='dateGraded', null=True, verbose_name='Date graded'),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='dateuploaded',
            field=models.DateField(db_column='dateUploaded', verbose_name='Upload date'),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='pointsearned',
            field=models.PositiveIntegerField(null=True, verbose_name='Points earned'),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auth.user', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='submission',
            field=models.FileField(upload_to='documents/', verbose_name='Submission'),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='teachernotes',
            field=models.TextField(db_column='teacherNotes', null=True, verbose_name='Teacher notes'),
        ),
    ]
