# Generated by Django 3.2 on 2021-06-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210607_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubmission',
            name='dateuploaded',
            field=models.DateField(db_column='dateuploaded', verbose_name='Upload date'),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='teachernotes',
            field=models.TextField(db_column='teachernotes', null=True, verbose_name='Teacher notes'),
        ),
    ]
