# Generated by Django 3.2 on 2021-06-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_studentsubmission_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubmission',
            name='submission',
            field=models.FileField(blank=True, default=1, upload_to='documents/', verbose_name='Submission'),
            preserve_default=False,
        ),
    ]
