# Generated by Django 3.2 on 2021-06-10 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_studentsubmission_dateuploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursestudent',
            name='grade',
        ),
    ]
