# Generated by Django 3.2 on 2021-04-09 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='course',
            name='term',
        ),
        migrations.RemoveField(
            model_name='coursestudents',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursestudents',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentassignemnts',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='studentassignemnts',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teachercertifications',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Assignments',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseName',
        ),
        migrations.DeleteModel(
            name='CourseStudents',
        ),
        migrations.DeleteModel(
            name='StudentAssignemnts',
        ),
        migrations.DeleteModel(
            name='TeacherCertifications',
        ),
        migrations.DeleteModel(
            name='Terms',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
